Repository nagul2/basic-sns-api, pull requests merged in 2025-04, with the labels that each got.

#14 [Auth] AuthService Transactional 적용하여 트랙잭션 관리
  src/main/java/com/sns/api/auth/service/impl/AuthServiceImpl.java
Labels: enhancement

#16 [Users] 내 정보 조회 API 구현
  .gitignore
  src/main/java/com/sns/api/users/controller/UsersController.java
  src/main/java/com/sns/api/users/service/UsersService.java
  src/main/java/com/sns/api/users/service/impl/UsersServiceImpl.java
Labels: enhancement

#18 뉴스피드 게시물 CRUD
  .gitignore
  src/main/java/com/sns/api/posts/controller/PostsController.java
  src/main/java/com/sns/api/posts/domain/dto/PostsDto.java
  src/main/java/com/sns/api/posts/domain/dto/request/PostCreateRequestDto.java
  src/main/java/com/sns/api/posts/domain/dto/request/PostUpdateRequestDto.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostResponseDto.java
  src/main/java/com/sns/api/posts/domain/entity/Posts.java
  src/main/java/com/sns/api/posts/repository/PostsRepository.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
  src/main/java/com/sns/common/config/PagingConfig.java
Labels: enhancement

#26 [Users] 회원 정보 수정, 조회 기능 구현
  src/main/java/com/sns/api/users/controller/UsersController.java
  src/main/java/com/sns/api/users/domain/dto/UserReadResponseDto.java
  src/main/java/com/sns/api/users/domain/dto/UserUpdateRequestDto.java
  src/main/java/com/sns/api/users/domain/entity/Users.java
  src/main/java/com/sns/api/users/repository/UsersRepository.java
  src/main/java/com/sns/api/users/service/UsersService.java
  src/main/java/com/sns/api/users/service/impl/UsersServiceImpl.java
Labels: enhancement

#27 [Posts] 게시물 기간별 검색 기능
  src/main/java/com/sns/api/posts/controller/PostsController.java
  src/main/java/com/sns/api/posts/domain/dto/request/PostSearchRequestDto.java
  src/main/java/com/sns/api/posts/repository/PostsRepository.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#28 [Friends] 친구 요청 수락/거절/취소 API 개발 및 친구 요청 API 방어로직 추가
  src/main/java/com/sns/api/friends/controller/FriendsController.java
  src/main/java/com/sns/api/friends/domain/dto/request/ActionFriendsRequestDto.java
  src/main/java/com/sns/api/friends/domain/dto/response/CommonFriendsResponseDto.java
  src/main/java/com/sns/api/friends/domain/entity/Friends.java
  src/main/java/com/sns/api/friends/domain/entity/FriendsStatus.java
  src/main/java/com/sns/api/friends/repository/FriendsRepository.java
  src/main/java/com/sns/api/friends/service/FriendsService.java
  src/main/java/com/sns/api/friends/service/impl/FriendsServiceImpl.java
Labels: enhancement

#32 [Comments] 댓글 CRUD 구현
  src/main/java/com/sns/api/comments/controller/CommentsController.java
  src/main/java/com/sns/api/comments/domain/dto/CommentsDto.java
  src/main/java/com/sns/api/comments/domain/dto/request/CommentCreateRequestDto.java
  src/main/java/com/sns/api/comments/domain/dto/request/CommentUpdateRequestDto.java
  src/main/java/com/sns/api/comments/domain/dto/response/CommentResponseDto.java
  src/main/java/com/sns/api/comments/domain/entity/Comments.java
  src/main/java/com/sns/api/comments/repository/CommentsRepository.java
  src/main/java/com/sns/api/comments/service/CommentsService.java
  src/main/java/com/sns/api/comments/service/impl/CommentsServiceImpl.java
Labels: enhancement

#33 [Friends]친구 삭제 API 개발 #29
  src/main/java/com/sns/api/friends/controller/FriendsController.java
  src/main/java/com/sns/api/friends/service/FriendsService.java
  src/main/java/com/sns/api/friends/service/impl/FriendsServiceImpl.java
Labels: enhancement

#36 [Posts, Comments][Refactor] 게시물, 댓글 리팩터링
  src/main/java/com/sns/api/comments/controller/CommentsController.java
  src/main/java/com/sns/api/posts/controller/PostsController.java
  src/main/java/com/sns/api/posts/domain/dto/request/PostCreateRequestDto.java
  src/main/java/com/sns/api/posts/domain/dto/request/PostUpdateRequestDto.java
  src/main/java/com/sns/api/posts/repository/PostsRepository.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#38 [Friends]내 친구 전체 조회 API 개발 #30
  src/main/java/com/sns/api/friends/controller/FriendsController.java
  src/main/java/com/sns/api/friends/domain/dto/response/FindFriendsResponseDto.java
  src/main/java/com/sns/api/friends/domain/entity/Friends.java
  src/main/java/com/sns/api/friends/repository/FriendsRepository.java
  src/main/java/com/sns/api/friends/service/FriendsService.java
  src/main/java/com/sns/api/friends/service/impl/FriendsServiceImpl.java
Labels: enhancement

#39 [Likes] 게시글 좋아요 CRD 구현
  src/main/java/com/sns/api/likes/controller/PostLikesController.java
  src/main/java/com/sns/api/likes/domain/dto/LikeCountResponseDto.java
  src/main/java/com/sns/api/likes/domain/dto/LikeResponseDto.java
  src/main/java/com/sns/api/likes/domain/entity/LikeType.java
  src/main/java/com/sns/api/likes/domain/entity/Likes.java
  src/main/java/com/sns/api/likes/repository/LikesRepository.java
  src/main/java/com/sns/api/likes/service/LikesService.java
  src/main/java/com/sns/api/likes/service/impl/LikesServiceImpl.java
Labels: enhancement

#43 [Posts] 게시물, 댓글 연동
  src/main/java/com/sns/api/comments/repository/CommentsRepository.java
  src/main/java/com/sns/api/posts/controller/PostsController.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostFlatDto.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostResponseDto.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostWithCommentsResponseDto.java
  src/main/java/com/sns/api/posts/repository/PostsRepository.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#46 Chore/#45 setup querydsl
  build.gradle
  src/main/java/com/sns/common/config/QuerydslConfig.java
Labels: enhancement

#47 [Follows] 팔로우 관련 로직 CRD
  src/main/java/com/sns/api/follow/controller/FollowsController.java
  src/main/java/com/sns/api/follow/domain/dto/request/FollowsRequestDto.java
  src/main/java/com/sns/api/follow/domain/dto/response/FollowsResponseDto.java
  src/main/java/com/sns/api/follow/domain/entity/Follows.java
  src/main/java/com/sns/api/follow/repository/FollowsRepository.java
  src/main/java/com/sns/api/follow/service/FollowsService.java
  src/main/java/com/sns/api/follow/service/impl/FollowsServiceImpl.java
Labels: enhancement

#49 [Follows] 팔로우, 팔로잉 페이지네이션
  src/main/java/com/sns/api/follow/controller/FollowsController.java
  src/main/java/com/sns/api/follow/repository/FollowsRepository.java
  src/main/java/com/sns/api/follow/service/FollowsService.java
  src/main/java/com/sns/api/follow/service/impl/FollowsServiceImpl.java
Labels: enhancement

#50 [Likes] 댓글 좋아요 CRD
  src/main/java/com/sns/api/likes/controller/CommentLikesController.java
  src/main/java/com/sns/api/likes/domain/dto/LikeCountResponseDto.java
  src/main/java/com/sns/api/likes/domain/dto/LikeResponseDto.java
  src/main/java/com/sns/api/likes/domain/entity/Likes.java
  src/main/java/com/sns/api/likes/service/impl/LikesServiceImpl.java
Labels: enhancement

#53 게시물, 좋아요 연동 + querydsl 적용
  src/main/java/com/sns/api/comments/repository/CommentsRepository.java
  src/main/java/com/sns/api/comments/service/impl/CommentsServiceImpl.java
  src/main/java/com/sns/api/common/domain/dto/UserBaseDto.java
  src/main/java/com/sns/api/posts/controller/PostsController.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostFlatDto.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostResponseDto.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostWithCommentsResponseDto.java
  src/main/java/com/sns/api/posts/repository/PostsRepository.java
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepository.java
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepositoryImpl.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#55 [Users] 회원 검색 시 친구 먼저 정렬되는 기능 추가
  src/main/java/com/sns/api/users/controller/UsersController.java
  src/main/java/com/sns/api/users/repository/UsersRepository.java
  src/main/java/com/sns/api/users/service/UsersService.java
  src/main/java/com/sns/api/users/service/impl/UsersServiceImpl.java
Labels: enhancement

#57 [Posts] 친구 게시물 우선 조회
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepositoryImpl.java
Labels: enhancement

#58 [Comments] 댓글, 좋아요 연동
  src/main/java/com/sns/api/comments/controller/CommentsController.java
  src/main/java/com/sns/api/comments/domain/dto/response/CommentResponseDto.java
  src/main/java/com/sns/api/comments/repository/CommentsRepository.java
  src/main/java/com/sns/api/comments/repository/query/CommentsQueryRepository.java
  src/main/java/com/sns/api/comments/repository/query/CommentsQueryRepositoryImpl.java
  src/main/java/com/sns/api/comments/service/CommentsService.java
  src/main/java/com/sns/api/comments/service/impl/CommentsServiceImpl.java
  src/main/java/com/sns/api/posts/domain/dto/response/PostWithCommentsResponseDto.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#63 [Friends][Fix]보낸 / 받은 친구 요청의 잘못 적용된 정렬 조건 수정
  src/main/java/com/sns/api/friends/repository/FriendsRepository.java
Labels: bug

#67 [Posts] 내가 좋아요한 게시글 목록 조회 구현
  src/main/java/com/sns/api/posts/controller/LikedPostController.java
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepository.java
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepositoryImpl.java
  src/main/java/com/sns/api/posts/service/PostsService.java
  src/main/java/com/sns/api/posts/service/impl/PostsServiceImpl.java
Labels: enhancement

#66 [Setting] 단위 테스트에서 id를 직접 세팅 할 수 있는 엔티티 전용 유틸 클래스 생성
  src/test/java/com/sns/util/TestEntityUtil.java
Labels: enhancement

#76 [Posts][Fix] 내가 좋아요한 게시글 목록이 최신순으로 정렬되지 않던 이슈 해결
  src/main/java/com/sns/api/posts/repository/query/PostQueryRepositoryImpl.java
Labels: bug

#78 [Docs] README 업데이트
  README.md
  documents/db-erd.png
Labels: documentation
